import {
  array,
  boolean,
  enums,
  format,
  type GuardType,
  integer,
  literal,
  number,
  optional,
  props,
  string,
} from 'https://raw.githubusercontent.com/systematic-trader/type-guard/main/mod.ts'
import { AssetType } from '../derives/asset-type.ts'
import { BondType } from '../derives/bond-type.ts'
import { BondsCouponType } from '../derives/bonds-coupon-type.ts'
import { Currency3 } from '../derives/currency.ts'
import { DaysType } from '../derives/days-type.ts'
import { DefaultSlippageType } from '../derives/default-slippage-type.ts'
import { DisplayHintType } from '../derives/display-hint-type.ts'
import { DistributionPolicy } from '../derives/distribution-policy.ts'
import { DividendPeriodicityType } from '../derives/dividend-periodicity-type.ts'
import { LotSizeType } from '../derives/lot-size-type.ts'
import { MutualFundAssetType } from '../derives/mutual-fund-asset-type.ts'
import { NonTradableReason } from '../derives/non-tradable-reason.ts'
import { OrderDurationType } from '../derives/order-duration-type.ts'
import { OrderTriggerPriceType } from '../derives/order-trigger-price-type.ts'
import { PlaceableOrderType } from '../derives/placeable-order-type.ts'
import { StrategyType } from '../derives/strategy-type.ts'
import { SupportedStrategyType } from '../derives/supported-strategy-type.ts'
import { TradingSignal } from '../derives/trading-signal.ts'
import { TradingStatus } from '../derives/trading-status.ts'
import { TradingUnitsPluralType, TradingUnitsSingularType } from '../derives/trading-units-type.ts'
import { UnderlyingTypeCategory } from '../derives/underlying-type-category.ts'
import { ExchangeSummary } from './exchange-summary.ts'
import { InstrumentKey } from './instrument-key.ts'
import { InstrumentTradeSessions } from './instrument-trade-sessions.ts'
import { IpoDetails } from './ipo-details.ts'
import { OrderDistances } from './order-distances.ts'
import { OrderSetting } from './order-setting.ts'
import { PriceDisplayFormat } from './price-display-format.ts'
import { RelatedOptionRoot } from './related-option-root.ts'
import { StrategyLeg } from './strategy-leg.ts'
import { SupportedOrderTypeSetting } from './supported-order-type-setting.ts'
import { TickSizeScheme } from './tick-size-scheme.ts'

// TODO
// 1. specify TradingStatus with specific literals
// 2. specify InstrumentKey with specific asset types
// 3. specify RelatedOptionRootsEnhanced with specific asset types

export type InstrumentDetailsType =
  | InstrumentDetailsBond
  | InstrumentDetailsCfdOnCompanyWarrant
  | InstrumentDetailsCfdOnEtc
  | InstrumentDetailsCfdOnEtf
  | InstrumentDetailsCfdOnEtn
  | InstrumentDetailsCfdOnFund
  | InstrumentDetailsCfdOnFutures
  | InstrumentDetailsCfdOnIndex
  | InstrumentDetailsCfdOnRights
  | InstrumentDetailsCfdOnStock
  | InstrumentDetailsCompanyWarrant
  | InstrumentDetailsContractFutures
  | InstrumentDetailsEtc
  | InstrumentDetailsEtf
  | InstrumentDetailsEtn
  | InstrumentDetailsFund
  | InstrumentDetailsFuturesStrategy
  | InstrumentDetailsFxForwards
  | InstrumentDetailsFxNoTouchOption
  | InstrumentDetailsFxOneTouchOption
  | InstrumentDetailsFxSpot // first!!
  | InstrumentDetailsFxSwap
  | InstrumentDetailsFxVanillaOption
  | InstrumentDetailsMutualFund
  | InstrumentDetailsRights
  | InstrumentDetailsStock
  | InstrumentDetailsStockIndex

export interface InstrumentDetailsBond extends GuardType<typeof InstrumentDetailsBond> {}
export const InstrumentDetailsBond = props({
  AssetType: AssetType.extract(['Bond']),
  AffiliateInfoRequired: boolean(),
  AmountDecimals: integer(),
  BondIndexRatio: number(),
  BondsMarginValue: number(),
  BondsReferenceRate: optional(string()),
  BondsTypes: optional(
    array(BondType.extract(['Convertible', 'DualCurrency', 'FloatingRateNote', 'InflationLinked', 'Perpetual'])),
  ),
  BondType: BondType.extract(['InflationLinked', 'NonInflationLinked']),
  Coupon: number(),
  CouponCurrency: optional(Currency3),
  CouponType: BondsCouponType.extract(['Fixed', 'Other', 'Variable']),
  CurrencyCode: Currency3,
  DefaultAmount: number(),
  DefaultSlippage: number(),
  DefaultSlippageType: DefaultSlippageType.extract(['Ticks']),
  Description: string(),
  Exchange: ExchangeSummary,
  ExpiryDate: format('gregorian-date'),
  Format: PriceDisplayFormat,
  GroupId: integer(),
  IncrementSize: number(),
  IsBailIn: optional(boolean()),
  IsBarrierEqualsStrike: boolean(),
  IsComplex: optional(boolean()),
  IsOcoOrderSupported: boolean(),
  IsPEAEligible: boolean(),
  IsPEASMEEligible: boolean(),
  IsRedemptionByAmounts: boolean(),
  IssueDate: format('date-iso8601'),
  IsSwitchBySameCurrency: boolean(),
  IsTradable: boolean(),
  LotSize: number(),
  LotSizeType: LotSizeType.extract(['NotUsed', 'OddLotsAllowed', 'OddLotsNotAllowed']),
  MinimumLotSize: optional(number()),
  MinimumTradeSize: optional(number()),
  NbbStatus: optional(enums(['None', 'XN', 'X'])),
  NonTradableReason: NonTradableReason.extract(['None', 'OfflineTradableBonds', 'ReduceOnlyInstrument']),
  OrderSetting: optional(OrderSetting),
  PriceToContractFactor: number(),
  RelatedInstruments: optional(array(InstrumentKey)),
  RelatedOptionRoots: optional(array(integer())),
  RelatedOptionRootsEnhanced: optional(array(RelatedOptionRoot)),
  StandardAmounts: optional(array(number())),
  SupportedOrderTypes: array(PlaceableOrderType.extract(['Limit', 'Market'])),
  SupportedOrderTypeSettings: array(props({
    DurationTypes: array(OrderDurationType.extract(['DayOrder', 'FillOrKill', 'GoodTillCancel', 'GoodTillDate'])),
    OrderType: PlaceableOrderType.extract(['Limit', 'Market']),
  })),
  Symbol: string(),
  TickSize: number(),
  TradableAs: optional(array(AssetType.extract(['Bond']))),
  TradableOn: array(format('positive-integer')),
  TradingSessions: InstrumentTradeSessions,
  TradingSignals: TradingSignal,
  TradingStatus: TradingStatus,
  Uic: integer(),
  UnderlyingAssetType: optional(AssetType.extract(['FxSpot', 'Stock'])),
  UnderlyingTypeCategory: UnderlyingTypeCategory,
  UnderlyingUic: optional(integer()),
})

export interface InstrumentDetailsCfdOnCompanyWarrant extends GuardType<typeof InstrumentDetailsCfdOnCompanyWarrant> {}
export const InstrumentDetailsCfdOnCompanyWarrant = props({
  AssetType: AssetType.extract(['CfdOnCompanyWarrant']),
  AffiliateInfoRequired: boolean(),
  AmountDecimals: integer(),
  CurrencyCode: Currency3,
  DefaultAmount: number(),
  DefaultSlippage: number(),
  DefaultSlippageType: DefaultSlippageType.extract(['Ticks']),
  Description: string(),
  Exchange: ExchangeSummary,
  Format: PriceDisplayFormat,
  FractionalMinimumLotSize: optional(number()),
  GroupId: integer(),
  IncrementSize: number(),
  IsBarrierEqualsStrike: boolean(),
  IsComplex: boolean(),
  IsExtendedTradingHoursEnabled: optional(boolean()),
  IsOcoOrderSupported: boolean(),
  IsPEAEligible: boolean(),
  IsPEASMEEligible: boolean(),
  IsRedemptionByAmounts: boolean(),
  IsSwitchBySameCurrency: boolean(),
  IsTradable: boolean(),
  LotSizeType: LotSizeType.extract(['NotUsed', 'OddLotsNotAllowed']),
  MinimumLotSize: optional(number()),
  MinimumTradeSize: optional(number()),
  NonTradableReason: NonTradableReason.extract(['None', 'NotOnlineClientTradable', 'ReduceOnlyInstrument']),
  OrderDistances: OrderDistances,
  // OrderSetting: OrderSetting,
  PriceCurrency: Currency3,
  PriceToContractFactor: optional(number()),
  PrimaryListing: optional(integer()),
  RelatedInstruments: array(InstrumentKey),
  ShortTradeDisabled: optional(boolean()),
  StandardAmounts: array(number()),
  // SupportedOrderTriggerPriceTypes: array(OrderTriggerPriceType),
  SupportedOrderTypes: array(
    PlaceableOrderType.extract(['Limit', 'Market', 'StopIfTraded', 'StopLimit', 'TrailingStopIfTraded']),
  ),
  SupportedOrderTypeSettings: array(props({
    DurationTypes: array(
      OrderDurationType.extract(['DayOrder', 'GoodTillCancel', 'GoodTillDate', 'ImmediateOrCancel']),
    ),
    OrderType: PlaceableOrderType.extract(['Limit', 'Market', 'StopIfTraded', 'StopLimit', 'TrailingStopIfTraded']),
  })),
  SupportedStrategies: optional(array(SupportedStrategyType)),
  Symbol: string(),
  TickSize: optional(number()),
  TickSizeScheme: optional(TickSizeScheme),
  TradableAs: optional(array(AssetType.extract(['CfdOnCompanyWarrant']))),
  TradableOn: array(format('positive-integer')),
  TradingSessions: InstrumentTradeSessions,
  TradingSignals: TradingSignal,
  TradingStatus: TradingStatus,
  Uic: integer(),
  UnderlyingTypeCategory: UnderlyingTypeCategory,
})

export interface InstrumentDetailsCfdOnEtc extends GuardType<typeof InstrumentDetailsCfdOnEtc> {}
export const InstrumentDetailsCfdOnEtc = props({
  AssetType: AssetType.extract(['CfdOnEtc']),
  AffiliateInfoRequired: boolean(),
  AmountDecimals: integer(),
  CurrencyCode: Currency3,
  DefaultAmount: number(),
  DefaultSlippage: number(),
  DefaultSlippageType: DefaultSlippageType.extract(['Ticks']),
  Description: string(),
  Exchange: ExchangeSummary,
  Format: PriceDisplayFormat,
  FractionalMinimumLotSize: number(),
  GroupId: integer(),
  IncrementSize: number(),
  IsBarrierEqualsStrike: boolean(),
  IsComplex: boolean(),
  IsExtendedTradingHoursEnabled: boolean(),
  IsOcoOrderSupported: boolean(),
  IsPEAEligible: boolean(),
  IsPEASMEEligible: boolean(),
  IsRedemptionByAmounts: boolean(),
  IsSwitchBySameCurrency: boolean(),
  IsTradable: boolean(),
  LotSizeType: LotSizeType.extract(['NotUsed', 'OddLotsNotAllowed']),
  MinimumLotSize: optional(number()),
  MinimumTradeSize: number(),
  NonTradableReason: NonTradableReason.extract(['None', 'ReduceOnlyInstrument']),
  OrderDistances: OrderDistances,
  PriceCurrency: Currency3,
  PriceToContractFactor: number(),
  PrimaryListing: optional(integer()),
  RelatedInstruments: array(InstrumentKey),
  ShortTradeDisabled: boolean(),
  StandardAmounts: array(number()),
  SupportedOrderTypes: array(
    PlaceableOrderType.extract(['Limit', 'Market', 'StopIfTraded', 'StopLimit', 'TrailingStopIfTraded']),
  ),
  SupportedOrderTypeSettings: array(props({
    DurationTypes: array(
      OrderDurationType.extract(['DayOrder', 'GoodTillCancel', 'GoodTillDate', 'ImmediateOrCancel']),
    ),
    OrderType: PlaceableOrderType.extract(['Market', 'Limit', 'StopLimit', 'StopIfTraded', 'TrailingStopIfTraded']),
  })),
  SupportedStrategies: array(
    SupportedStrategyType.extract([
      'Dark',
      'Iceberg',
      'Implementation Shortfall',
      'Limit on Close (LOC)',
      'Liquidity Seeking',
      'Market on Close (MOC)',
      'Price Peg',
      'Target Close',
      'TWAP',
      'VWAP',
      'With Volume',
    ]),
  ),
  Symbol: string(),
  TickSize: optional(number()),
  TickSizeScheme: optional(TickSizeScheme),
  TradableAs: array(AssetType.extract(['CfdOnEtc'])),
  TradableOn: array(format('positive-integer')),
  TradingSessions: InstrumentTradeSessions,
  TradingSignals: TradingSignal,
  TradingStatus: TradingStatus,
  Uic: integer(),
  UnderlyingTypeCategory: UnderlyingTypeCategory,
})

export interface InstrumentDetailsCfdOnEtf extends GuardType<typeof InstrumentDetailsCfdOnEtf> {}
export const InstrumentDetailsCfdOnEtf = props({
  AssetType: literal('CfdOnEtf'),
  AffiliateInfoRequired: boolean(),
  AmountDecimals: integer(),
  CurrencyCode: Currency3,
  DefaultAmount: number(),
  DefaultSlippage: number(),
  DefaultSlippageType: DefaultSlippageType.extract(['Ticks']),
  Description: string(),
  Exchange: ExchangeSummary,
  Format: PriceDisplayFormat,
  FractionalMinimumLotSize: optional(number()),
  GroupId: integer(),
  IncrementSize: number(),
  IsBarrierEqualsStrike: boolean(),
  IsComplex: boolean(),
  IsExtendedTradingHoursEnabled: optional(boolean()),
  IsOcoOrderSupported: boolean(),
  IsPEAEligible: boolean(),
  IsPEASMEEligible: boolean(),
  IsRedemptionByAmounts: boolean(),
  IsSwitchBySameCurrency: boolean(),
  IsTradable: boolean(),
  LotSize: optional(number()),
  LotSizeType: LotSizeType.extract(['NotUsed', 'OddLotsNotAllowed']),
  MinimumLotSize: optional(number()),
  MinimumTradeSize: optional(number()),
  NonTradableReason: NonTradableReason.extract(['None', 'NotOnlineClientTradable', 'ReduceOnlyInstrument']),
  OrderDistances: OrderDistances,
  PriceCurrency: Currency3,
  PriceToContractFactor: optional(number()),
  PrimaryListing: optional(integer()),
  RelatedInstruments: optional(array(InstrumentKey)),
  RelatedOptionRoots: optional(array(integer())),
  RelatedOptionRootsEnhanced: optional(array(RelatedOptionRoot)),
  ShortTradeDisabled: optional(boolean()),
  StandardAmounts: array(number()),
  SupportedOrderTypes: array(
    PlaceableOrderType.extract(['Limit', 'Market', 'StopLimit', 'StopIfTraded', 'TrailingStopIfTraded']),
  ),
  SupportedOrderTypeSettings: array(props({
    DurationTypes: array(
      OrderDurationType.extract(['DayOrder', 'GoodTillCancel', 'GoodTillDate', 'ImmediateOrCancel']),
    ),
    OrderType: PlaceableOrderType.extract(['Limit', 'Market', 'StopLimit', 'StopIfTraded', 'TrailingStopIfTraded']),
  })),
  SupportedStrategies: array(
    SupportedStrategyType.extract([
      'Dark',
      'Iceberg',
      'Implementation Shortfall',
      'Limit on Close (LOC)',
      'Liquidity Seeking',
      'Market on Close (MOC)',
      'Pre-Market Limit',
      'Price Peg',
      'Target Close',
      'TWAP',
      'VWAP',
      'With Volume',
    ]),
  ),
  Symbol: string(),
  TickSize: optional(number()),
  TickSizeScheme: optional(TickSizeScheme),
  TradableAs: optional(array(AssetType.extract(['CfdOnEtf']))),
  TradableOn: array(format('positive-integer')),
  TradingSessions: InstrumentTradeSessions,
  TradingSignals: TradingSignal,
  TradingStatus: TradingStatus,
  Uic: integer(),
  UnderlyingTypeCategory: UnderlyingTypeCategory,
})

export interface InstrumentDetailsCfdOnEtn extends GuardType<typeof InstrumentDetailsCfdOnEtn> {}
export const InstrumentDetailsCfdOnEtn = props({
  AssetType: AssetType.extract(['CfdOnEtn']),
  AffiliateInfoRequired: boolean(),
  AmountDecimals: integer(),
  CurrencyCode: Currency3,
  DefaultAmount: number(),
  DefaultSlippage: number(),
  DefaultSlippageType: DefaultSlippageType.extract(['Ticks']),
  Description: string(),
  Exchange: ExchangeSummary,
  Format: PriceDisplayFormat,
  FractionalMinimumLotSize: number(),
  GroupId: integer(),
  IncrementSize: number(),
  IsBarrierEqualsStrike: boolean(),
  IsComplex: boolean(),
  IsExtendedTradingHoursEnabled: boolean(),
  IsOcoOrderSupported: boolean(),
  IsPEAEligible: boolean(),
  IsPEASMEEligible: boolean(),
  IsRedemptionByAmounts: boolean(),
  IsSwitchBySameCurrency: boolean(),
  IsTradable: boolean(),
  LotSizeType: LotSizeType.extract(['NotUsed', 'OddLotsNotAllowed']),
  MinimumLotSize: optional(number()),
  MinimumTradeSize: number(),
  NonTradableReason: NonTradableReason.extract(['None']),
  OrderDistances: OrderDistances,
  PriceCurrency: Currency3,
  PriceToContractFactor: number(),
  PrimaryListing: optional(integer()),
  RelatedInstruments: array(InstrumentKey),
  RelatedOptionRoots: optional(array(integer())),
  RelatedOptionRootsEnhanced: optional(array(RelatedOptionRoot)),
  ShortTradeDisabled: boolean(),
  StandardAmounts: array(number()),
  SupportedOrderTypes: array(
    PlaceableOrderType.extract([
      'Limit',
      'Market',
      'StopIfTraded',
      'StopLimit',
      'TrailingStopIfTraded',
    ]),
  ),
  SupportedOrderTypeSettings: array(props({
    DurationTypes: array(
      OrderDurationType.extract(['DayOrder', 'GoodTillCancel', 'GoodTillDate', 'ImmediateOrCancel']),
    ),
    OrderType: PlaceableOrderType.extract(['Limit', 'Market', 'StopLimit', 'StopIfTraded', 'TrailingStopIfTraded']),
  })),
  SupportedStrategies: array(
    SupportedStrategyType.extract([
      'Dark',
      'Iceberg',
      'Implementation Shortfall',
      'Limit on Close (LOC)',
      'Liquidity Seeking',
      'Market on Close (MOC)',
      'Pre-Market Limit',
      'Price Peg',
      'Target Close',
      'TWAP',
      'VWAP',
      'With Volume',
    ]),
  ),
  Symbol: string(),
  TickSize: optional(number()),
  TickSizeScheme: optional(TickSizeScheme),
  TradableAs: array(AssetType.extract(['CfdOnEtn'])),
  TradableOn: array(format('positive-integer')),
  TradingSessions: InstrumentTradeSessions,
  TradingSignals: TradingSignal,
  TradingStatus: TradingStatus,
  Uic: integer(),
  UnderlyingTypeCategory: UnderlyingTypeCategory,
})

export interface InstrumentDetailsCfdOnFund extends GuardType<typeof InstrumentDetailsCfdOnFund> {}
export const InstrumentDetailsCfdOnFund = props({
  AssetType: AssetType.extract(['CfdOnFund']),
  AffiliateInfoRequired: boolean(),
  AmountDecimals: integer(),
  CurrencyCode: Currency3,
  DefaultAmount: number(),
  DefaultSlippage: number(),
  DefaultSlippageType: DefaultSlippageType.extract(['Ticks']),
  Description: string(),
  Exchange: ExchangeSummary,
  Format: PriceDisplayFormat,
  FractionalMinimumLotSize: number(),
  GroupId: integer(),
  IncrementSize: number(),
  IsBarrierEqualsStrike: boolean(),
  IsComplex: boolean(),
  IsExtendedTradingHoursEnabled: boolean(),
  IsOcoOrderSupported: boolean(),
  IsPEAEligible: boolean(),
  IsPEASMEEligible: boolean(),
  IsRedemptionByAmounts: boolean(),
  IsSwitchBySameCurrency: boolean(),
  IsTradable: boolean(),
  LotSizeType: LotSizeType.extract(['NotUsed', 'OddLotsNotAllowed']),
  MinimumLotSize: optional(number()),
  MinimumTradeSize: number(),
  NonTradableReason: NonTradableReason.extract(['None', 'ReduceOnlyInstrument']),
  OrderDistances: OrderDistances,
  PriceCurrency: Currency3,
  PriceToContractFactor: number(),
  PrimaryListing: optional(integer()),
  RelatedInstruments: array(InstrumentKey),
  ShortTradeDisabled: boolean(),
  StandardAmounts: array(number()),
  SupportedOrderTypes: array(
    PlaceableOrderType.extract(['Market', 'Limit', 'StopLimit', 'StopIfTraded', 'TrailingStopIfTraded']),
  ),
  SupportedOrderTypeSettings: array(props({
    DurationTypes: array(
      OrderDurationType.extract(['DayOrder', 'GoodTillCancel', 'GoodTillDate', 'ImmediateOrCancel']),
    ),
    OrderType: PlaceableOrderType.extract(['Market', 'Limit', 'StopLimit', 'StopIfTraded', 'TrailingStopIfTraded']),
  })),
  SupportedStrategies: array(
    SupportedStrategyType.extract([
      'Dark',
      'Iceberg',
      'Implementation Shortfall',
      'Limit on Close (LOC)',
      'Liquidity Seeking',
      'Market on Close (MOC)',
      'Pre-Market Limit',
      'Price Peg',
      'Target Close',
      'TWAP',
      'VWAP',
      'With Volume',
    ]),
  ),
  Symbol: string(),
  TickSize: optional(number()),
  TickSizeScheme: optional(TickSizeScheme),
  TradableAs: array(AssetType.extract(['CfdOnFund'])),
  TradableOn: array(format('positive-integer')),
  TradingSessions: InstrumentTradeSessions,
  TradingSignals: TradingSignal,
  TradingStatus: TradingStatus,
  Uic: integer(),
  UnderlyingTypeCategory: UnderlyingTypeCategory,
})

export interface InstrumentDetailsCfdOnFutures extends GuardType<typeof InstrumentDetailsCfdOnFutures> {}
export const InstrumentDetailsCfdOnFutures = props({
  AssetType: AssetType.extract(['CfdOnFutures']),
  AffiliateInfoRequired: boolean(),
  AmountDecimals: integer(),
  CurrencyCode: Currency3,
  DefaultAmount: number(),
  DefaultSlippage: optional(number()),
  DefaultSlippageType: optional(DefaultSlippageType.extract(['Percentage'])),
  Description: string(),
  DisplayHint: optional(DisplayHintType.extract(['Continuous', 'StockIndices', 'Interests', 'Forex'])),
  ExpiryDate: format('gregorian-date'),
  ExpiryDateTime: format('date-iso8601'),
  Format: PriceDisplayFormat,
  GroupId: integer(),
  IncrementSize: number(),
  IsBarrierEqualsStrike: boolean(),
  IsComplex: optional(boolean()),
  IsOcoOrderSupported: boolean(),
  IsPEAEligible: boolean(),
  IsPEASMEEligible: boolean(),
  IsRedemptionByAmounts: boolean(),
  IsSwitchBySameCurrency: boolean(),
  IsTradable: boolean(),
  LotSize: number(),
  LotSizeType: LotSizeType.extract(['OddLotsNotAllowed']),
  MinimumLotSize: number(),
  MinimumOrderValue: number(),
  NonTradableReason: NonTradableReason.extract(['None', 'NotOnlineClientTradable']),
  OrderDistances: optional(OrderDistances),
  PriceCurrency: Currency3,
  PriceToContractFactor: number(),
  PrimaryListing: optional(integer()),
  RelatedInstruments: optional(array(InstrumentKey)),
  RelatedOptionRoots: optional(array(integer())),
  RelatedOptionRootsEnhanced: optional(array(RelatedOptionRoot)),
  StandardAmounts: optional(array(number())),
  SupportedOrderTypes: array(
    PlaceableOrderType.extract(['Limit', 'Market', 'StopLimit', 'StopIfTraded', 'TrailingStopIfTraded']),
  ),
  SupportedOrderTypeSettings: array(props({
    DurationTypes: array(
      OrderDurationType.extract(['DayOrder', 'GoodTillCancel', 'GoodTillDate', 'ImmediateOrCancel']),
    ),
    OrderType: PlaceableOrderType.extract(['Limit', 'Market', 'StopLimit', 'StopIfTraded', 'TrailingStopIfTraded']),
  })),
  Symbol: string(),
  TickSize: number(),
  TradableAs: optional(array(AssetType.extract(['CfdOnFutures']))),
  TradableOn: optional(array(format('positive-integer'))),
  TradingSessions: InstrumentTradeSessions,
  TradingSignals: TradingSignal,
  TradingStatus: TradingStatus,
  TradingUnitsPlural: optional(TradingUnitsPluralType),
  TradingUnitsSingular: optional(TradingUnitsSingularType),
  Uic: integer(),
  UnderlyingTypeCategory: optional(UnderlyingTypeCategory),
  UnderlyingUic: integer(),
})

export interface InstrumentDetailsCfdOnIndex extends GuardType<typeof InstrumentDetailsCfdOnIndex> {}
export const InstrumentDetailsCfdOnIndex = props({
  AssetType: AssetType.extract(['CfdOnIndex']),
  AffiliateInfoRequired: boolean(),
  AmountDecimals: integer(),
  CurrencyCode: Currency3,
  DefaultAmount: number(),
  DefaultSlippage: number(),
  DefaultSlippageType: DefaultSlippageType.extract(['Percentage']),
  Description: string(),
  Format: PriceDisplayFormat,
  GroupId: integer(),
  IncrementSize: number(),
  IsBarrierEqualsStrike: boolean(),
  IsComplex: boolean(),
  IsOcoOrderSupported: boolean(),
  IsPEAEligible: boolean(),
  IsPEASMEEligible: boolean(),
  IsRedemptionByAmounts: boolean(),
  IsSwitchBySameCurrency: boolean(),
  IsTradable: boolean(),
  LotSizeType: LotSizeType.extract(['NotUsed', 'OddLotsNotAllowed']),
  MinimumLotSize: optional(number()),
  NonTradableReason: NonTradableReason.extract(['None']),
  OrderDistances: OrderDistances,
  PriceToContractFactor: number(),
  RelatedInstruments: array(InstrumentKey),
  RelatedOptionRoots: optional(array(integer())),
  RelatedOptionRootsEnhanced: optional(array(RelatedOptionRoot)),
  StandardAmounts: array(number()),
  SupportedOrderTypes: array(
    PlaceableOrderType.extract(['Limit', 'Market', 'StopLimit', 'StopIfTraded', 'TrailingStopIfTraded']),
  ),
  SupportedOrderTypeSettings: array(props({
    DurationTypes: array(
      OrderDurationType.extract(['DayOrder', 'GoodTillCancel', 'GoodTillDate', 'ImmediateOrCancel']),
    ),
    OrderType: PlaceableOrderType.extract(['Limit', 'Market', 'StopLimit', 'StopIfTraded', 'TrailingStopIfTraded']),
  })),
  Symbol: string(),
  TickSize: number(),
  TradableAs: array(AssetType.extract(['CfdOnIndex'])),
  TradableOn: array(format('positive-integer')),
  TradingSessions: InstrumentTradeSessions,
  TradingSignals: TradingSignal,
  TradingStatus: TradingStatus,
  Uic: integer(),
  UnderlyingTypeCategory: UnderlyingTypeCategory,
  UnderlyingUic: integer(),
})

export interface InstrumentDetailsCfdOnRights extends GuardType<typeof InstrumentDetailsCfdOnRights> {}
export const InstrumentDetailsCfdOnRights = props({
  AssetType: AssetType.extract(['CfdOnRights']),
  AffiliateInfoRequired: boolean(),
  AmountDecimals: integer(),
  CurrencyCode: Currency3,
  DefaultAmount: number(),
  DefaultSlippage: number(),
  DefaultSlippageType: DefaultSlippageType.extract(['Ticks']),
  Description: string(),
  Exchange: ExchangeSummary,
  Format: PriceDisplayFormat,
  GroupId: integer(),
  IncrementSize: number(),
  IsBarrierEqualsStrike: boolean(),
  IsComplex: boolean(),
  IsOcoOrderSupported: boolean(),
  IsPEAEligible: boolean(),
  IsPEASMEEligible: boolean(),
  IsRedemptionByAmounts: boolean(),
  IsSwitchBySameCurrency: boolean(),
  IsTradable: boolean(),
  LotSizeType: LotSizeType.extract(['NotUsed', 'OddLotsNotAllowed']),
  MinimumLotSize: optional(number()),
  NonTradableReason: NonTradableReason.extract(['NotOnlineClientTradable']),
  OrderDistances: OrderDistances,
  PriceCurrency: Currency3,
  PrimaryListing: optional(integer()),
  RelatedInstruments: array(InstrumentKey),
  ShortTradeDisabled: optional(boolean()),
  StandardAmounts: array(number()),
  SupportedOrderTypes: array(
    PlaceableOrderType.extract(['Limit', 'Market', 'StopLimit', 'StopIfTraded', 'TrailingStopIfTraded']),
  ),
  SupportedOrderTypeSettings: array(props({
    DurationTypes: array(
      OrderDurationType.extract(['DayOrder', 'GoodTillCancel', 'GoodTillDate', 'ImmediateOrCancel']),
    ),
    OrderType: PlaceableOrderType.extract(['Limit', 'Market', 'StopLimit', 'StopIfTraded', 'TrailingStopIfTraded']),
  })),
  SupportedStrategies: array(
    SupportedStrategyType.extract([
      'Dark',
      'Iceberg',
      'Implementation Shortfall',
      'Limit on Close (LOC)',
      'Liquidity Seeking',
      'Market on Close (MOC)',
      'Pre-Market Limit',
      'Price Peg',
      'Target Close',
      'TWAP',
      'VWAP',
      'With Volume',
    ]),
  ),
  Symbol: string(),
  TickSize: optional(integer()),
  TickSizeScheme: optional(TickSizeScheme),
  TradableAs: optional(array(AssetType.extract(['CfdOnRights']))),
  TradableOn: array(format('positive-integer')),
  TradingSessions: InstrumentTradeSessions,
  TradingSignals: TradingSignal,
  TradingStatus: TradingStatus,
  Uic: integer(),
  UnderlyingTypeCategory: UnderlyingTypeCategory,
})

export interface InstrumentDetailsCfdOnStock extends GuardType<typeof InstrumentDetailsCfdOnStock> {}
export const InstrumentDetailsCfdOnStock = props({
  AssetType: AssetType.extract(['CfdOnStock']),
  AffiliateInfoRequired: boolean(),
  AmountDecimals: integer(),
  CurrencyCode: Currency3,
  DefaultAmount: number(),
  DefaultSlippage: number(),
  DefaultSlippageType: DefaultSlippageType.extract(['Ticks']),
  Description: string(),
  Exchange: ExchangeSummary,
  Format: PriceDisplayFormat,
  FractionalMinimumLotSize: optional(number()),
  GroupId: integer(),
  IncrementSize: number(),
  IsBarrierEqualsStrike: boolean(),
  IsComplex: boolean(),
  IsExtendedTradingHoursEnabled: optional(boolean()),
  IsOcoOrderSupported: boolean(),
  IsPEAEligible: boolean(),
  IsPEASMEEligible: boolean(),
  IsRedemptionByAmounts: boolean(),
  IsSwitchBySameCurrency: boolean(),
  IsTradable: boolean(),
  LotSize: optional(number()),
  LotSizeType: LotSizeType.extract(['NotUsed', 'OddLotsNotAllowed']),
  MinimumLotSize: optional(number()),
  MinimumOrderValue: optional(number()),
  MinimumTradeSize: optional(number()),
  NonTradableReason: NonTradableReason.extract(['None', 'NotOnlineClientTradable', 'ReduceOnlyInstrument']),
  OrderDistances: OrderDistances,
  PriceCurrency: Currency3,
  PriceToContractFactor: optional(number()),
  PrimaryListing: optional(integer()),
  RelatedInstruments: optional(array(InstrumentKey)),
  RelatedOptionRoots: optional(array(integer())),
  RelatedOptionRootsEnhanced: optional(array(RelatedOptionRoot)),
  ShortTradeDisabled: optional(boolean()),
  StandardAmounts: array(number()),
  SupportedOrderTypes: array(
    PlaceableOrderType.extract(['Limit', 'Market', 'StopLimit', 'StopIfTraded', 'TrailingStopIfTraded']),
  ),
  SupportedOrderTypeSettings: array(props({
    DurationTypes: array(
      OrderDurationType.extract(['DayOrder', 'GoodTillCancel', 'GoodTillDate', 'ImmediateOrCancel']),
    ),
    OrderType: PlaceableOrderType.extract(['Limit', 'Market', 'StopLimit', 'StopIfTraded', 'TrailingStopIfTraded']),
  })),
  SupportedStrategies: optional(
    array(
      SupportedStrategyType.extract([
        'Dark',
        'Iceberg',
        'Implementation Shortfall',
        'Limit on Close (LOC)',
        'Liquidity Seeking',
        'Market on Close (MOC)',
        'Pre-Market Limit',
        'Price Peg',
        'Target Close',
        'TWAP',
        'VWAP',
        'With Volume',
      ]),
    ),
  ),
  Symbol: string(),
  TickSize: optional(number()),
  TickSizeScheme: optional(TickSizeScheme),
  TradableAs: optional(array(AssetType.extract(['CfdOnStock']))),
  TradableOn: array(format('positive-integer')),
  TradingSessions: InstrumentTradeSessions,
  TradingSignals: TradingSignal,
  TradingStatus: TradingStatus,
  Uic: integer(),
  UnderlyingTypeCategory: UnderlyingTypeCategory,
})

export interface InstrumentDetailsCompanyWarrant extends GuardType<typeof InstrumentDetailsCompanyWarrant> {}
export const InstrumentDetailsCompanyWarrant = props({
  AssetType: AssetType.extract(['CompanyWarrant']),
  AffiliateInfoRequired: boolean(),
  AmountDecimals: integer(),
  CurrencyCode: Currency3,
  DefaultAmount: number(),
  DefaultSlippage: number(),
  DefaultSlippageType: DefaultSlippageType.extract(['Ticks']),
  Description: string(),
  Exchange: ExchangeSummary,
  Format: PriceDisplayFormat,
  FractionalMinimumLotSize: optional(number()),
  GroupId: integer(),
  IncrementSize: number(),
  IsBailIn: optional(boolean()),
  IsBarrierEqualsStrike: boolean(),
  IsComplex: boolean(),
  IsExtendedTradingHoursEnabled: optional(boolean()),
  IsOcoOrderSupported: boolean(),
  IsPEAEligible: boolean(),
  IsPEASMEEligible: boolean(),
  IsRedemptionByAmounts: boolean(),
  IsSwitchBySameCurrency: boolean(),
  IsTradable: boolean(),
  LotSize: optional(number()),
  LotSizeType: LotSizeType.extract(['NotUsed', 'OddLotsNotAllowed']),
  MinimumLotSize: optional(number()),
  MinimumTradeSize: optional(number()),
  NonTradableReason: NonTradableReason.extract(['None', 'NotOnlineClientTradable', 'ReduceOnlyInstrument']),
  OrderDistances: OrderDistances,
  OrderSetting: optional(OrderSetting),
  PriceCurrency: Currency3,
  PriceToContractFactor: optional(number()),
  PrimaryListing: optional(integer()),
  RelatedInstruments: optional(array(InstrumentKey)),
  StandardAmounts: array(number()),
  SupportedOrderTriggerPriceTypes: optional(array(OrderTriggerPriceType.extract(['LastTraded', 'Open']))),
  SupportedOrderTypes: array(
    PlaceableOrderType.extract([
      'Limit',
      'Market',
      'StopLimit',
      'StopIfTraded',
      'TrailingStopIfTraded',
      'TriggerBreakout',
      'TriggerStop',
      'TriggerLimit',
    ]),
  ),
  SupportedOrderTypeSettings: array(props({
    DurationTypes: array(
      OrderDurationType.extract(['DayOrder', 'GoodTillCancel', 'GoodTillDate', 'ImmediateOrCancel']),
    ),
    OrderType: PlaceableOrderType.extract([
      'Limit',
      'Market',
      'StopLimit',
      'StopIfTraded',
      'TrailingStopIfTraded',
      'TriggerBreakout',
      'TriggerLimit',
      'TriggerStop',
    ]),
  })),
  SupportedStrategies: optional(
    array(
      SupportedStrategyType.extract([
        'Dark',
        'Iceberg',
        'Implementation Shortfall',
        'Limit on Close (LOC)',
        'Liquidity Seeking',
        'Market on Close (MOC)',
        'Pre-Market Limit',
        'Price Peg',
        'Target Close',
        'TWAP',
        'VWAP',
        'With Volume',
      ]),
    ),
  ),
  Symbol: string(),
  TickSize: optional(number()),
  TickSizeScheme: optional(TickSizeScheme),
  TradableAs: optional(array(AssetType.extract(['CompanyWarrant']))),
  TradableOn: array(format('positive-integer')),
  TradingSessions: InstrumentTradeSessions,
  TradingSignals: TradingSignal,
  TradingStatus: TradingStatus,
  Uic: integer(),
  UnderlyingTypeCategory: UnderlyingTypeCategory,
})

export interface InstrumentDetailsContractFutures extends GuardType<typeof InstrumentDetailsContractFutures> {}
export const InstrumentDetailsContractFutures = props({
  AssetType: AssetType.extract(['ContractFutures']),
  AffiliateInfoRequired: boolean(),
  AmountDecimals: integer(),
  ContractSize: integer({ minimum: 1 }),
  CurrencyCode: Currency3,
  DefaultAmount: number(),
  DefaultSlippage: number(),
  DefaultSlippageType: DefaultSlippageType.extract(['Ticks']),
  Description: string(),
  DisplayHint: optional(DisplayHintType.extract(['Continuous'])),
  Exchange: ExchangeSummary,
  ExpiryDate: format('gregorian-date'),
  Format: PriceDisplayFormat,
  GroupId: integer(),
  IncrementSize: number(),
  IsBarrierEqualsStrike: boolean(),
  IsComplex: boolean(),
  IsOcoOrderSupported: boolean(),
  IsPEAEligible: boolean(),
  IsPEASMEEligible: boolean(),
  IsPitTraded: boolean(),
  IsRedemptionByAmounts: boolean(),
  IsSwitchBySameCurrency: boolean(),
  IsTradable: boolean(),
  LotSizeText: optional(string()),
  LotSizeType: LotSizeType.extract(['NotUsed', 'OddLotsNotAllowed']),
  MinimumLotSize: optional(number()),
  MinimumTradeSize: number(),
  NonTradableReason: NonTradableReason.extract(['None', 'NotOnlineClientTradable', 'ReduceOnlyInstrument']),
  NoticeDate: optional(format('gregorian-date')),
  OrderDistances: OrderDistances,
  PriceToContractFactor: number(),
  PriceCurrency: optional(Currency3),
  PrimaryListing: optional(integer()),
  RelatedInstruments: optional(array(InstrumentKey)),
  RelatedOptionRoots: optional(array(integer())),
  RelatedOptionRootsEnhanced: optional(array(RelatedOptionRoot)),
  StandardAmounts: array(number()),
  SupportedOrderTriggerPriceTypes: array(OrderTriggerPriceType.extract(['LastTraded', 'Open'])),
  SupportedOrderTypes: array(
    PlaceableOrderType.extract([
      'Limit',
      'Market',
      'StopLimit',
      'StopIfTraded',
      'TrailingStopIfTraded',
      'TriggerBreakout',
      'TriggerLimit',
      'TriggerStop',
    ]),
  ),
  SupportedOrderTypeSettings: array(props({
    DurationTypes: array(
      OrderDurationType.extract(['DayOrder', 'GoodTillCancel', 'GoodTillDate']),
    ),
    OrderType: PlaceableOrderType.extract([
      'Limit',
      'Market',
      'StopLimit',
      'StopIfTraded',
      'TrailingStopIfTraded',
      'TriggerBreakout',
      'TriggerLimit',
      'TriggerStop',
    ]),
  })),
  SupportedStrategies: optional(
    array(
      SupportedStrategyType.extract([
        'Iceberg (Futures)',
        'Price Peg (Futures)',
        'Target Close (Futures)',
        'TWAP (Futures)',
        'VWAP (Futures)',
        'With Volume (Futures)',
      ]),
    ),
  ),
  Symbol: string(),
  TickSize: number(),
  TradableAs: optional(array(AssetType.extract(['ContractFutures']))),
  TradableOn: optional(array(format('positive-integer'))),
  TradingSessions: InstrumentTradeSessions,
  TradingSignals: TradingSignal,
  TradingStatus: TradingStatus,
  Uic: integer(),
  UnderlyingTypeCategory: UnderlyingTypeCategory,
})

export interface InstrumentDetailsEtc extends GuardType<typeof InstrumentDetailsEtc> {}
export const InstrumentDetailsEtc = props({
  AssetType: AssetType.extract(['Etc']),
  AffiliateInfoRequired: boolean(),
  AmountDecimals: integer(),
  CurrencyCode: Currency3,
  DefaultAmount: number(),
  DefaultSlippage: number(),
  DefaultSlippageType: DefaultSlippageType.extract(['Ticks']),
  Description: string(),
  Exchange: ExchangeSummary,
  Format: PriceDisplayFormat,
  FractionalMinimumLotSize: optional(number()),
  GroupId: integer(),
  IncrementSize: number(),
  IsBailIn: optional(boolean()),
  IsBarrierEqualsStrike: boolean(),
  IsComplex: boolean(),
  IsExtendedTradingHoursEnabled: optional(boolean()),
  IsOcoOrderSupported: boolean(),
  IsPEAEligible: boolean(),
  IsPEASMEEligible: boolean(),
  IsRedemptionByAmounts: boolean(),
  IsSwitchBySameCurrency: boolean(),
  IsSystematicInternaliser: boolean(),
  IsTradable: boolean(),
  LotSizeType: LotSizeType.extract(['NotUsed', 'OddLotsNotAllowed']),
  MinimumLotSize: optional(number()),
  MinimumTradeSize: optional(number()),
  NonTradableReason: NonTradableReason,
  OrderDistances: OrderDistances,
  OrderSetting: optional(OrderSetting),
  PriceCurrency: Currency3,
  PriceToContractFactor: optional(number()),
  PrimaryListing: optional(integer()),
  RelatedInstruments: optional(array(InstrumentKey)),
  RelatedOptionRoots: optional(array(integer())),
  RelatedOptionRootsEnhanced: optional(array(RelatedOptionRoot)),
  StandardAmounts: array(number()),
  SupportedOrderTriggerPriceTypes: optional(array(OrderTriggerPriceType.extract(['LastTraded', 'Open']))),
  SupportedOrderTypes: array(
    PlaceableOrderType.extract([
      'Limit',
      'Market',
      'StopLimit',
      'StopIfTraded',
      'TrailingStopIfTraded',
      'TriggerBreakout',
      'TriggerLimit',
      'TriggerStop',
    ]),
  ),
  SupportedOrderTypeSettings: array(props({
    DurationTypes: array(
      OrderDurationType.extract(['DayOrder', 'GoodTillCancel', 'GoodTillDate', 'ImmediateOrCancel']),
    ),
    OrderType: PlaceableOrderType.extract([
      'Limit',
      'Market',
      'StopLimit',
      'StopIfTraded',
      'TrailingStopIfTraded',
      'TriggerBreakout',
      'TriggerLimit',
      'TriggerStop',
    ]),
  })),
  SupportedStrategies: optional(
    array(
      SupportedStrategyType.extract([
        'Dark',
        'Iceberg',
        'Implementation Shortfall',
        'Limit on Close (LOC)',
        'Liquidity Seeking',
        'Market on Close (MOC)',
        'Price Peg',
        'Target Close',
        'TWAP',
        'VWAP',
        'With Volume',
      ]),
    ),
  ),
  Symbol: string(),
  TickSize: optional(number()),
  TickSizeScheme: optional(TickSizeScheme),
  TradableAs: optional(array(AssetType.extract(['Etc']))),
  TradableOn: array(format('positive-integer')),
  TradingSessions: InstrumentTradeSessions,
  TradingSignals: TradingSignal,
  TradingStatus: TradingStatus,
  Uic: integer(),
  UnderlyingTypeCategory: UnderlyingTypeCategory,
})

export interface InstrumentDetailsEtf extends GuardType<typeof InstrumentDetailsEtf> {}
export const InstrumentDetailsEtf = props({
  AssetType: AssetType.extract(['Etf']),
  AffiliateInfoRequired: boolean(),
  AmountDecimals: integer(),
  CanParticipateIn: optional(array(enums(['SavingsPlan']))),
  CurrencyCode: Currency3,
  DefaultAmount: number(),
  DefaultSlippage: number(),
  DefaultSlippageType: DefaultSlippageType.extract(['Ticks']),
  Description: string(),
  Exchange: ExchangeSummary,
  Format: PriceDisplayFormat,
  FractionalMinimumLotSize: optional(number()),
  GroupId: integer(),
  IncrementSize: number(),
  IsBailIn: optional(boolean()),
  IsBarrierEqualsStrike: boolean(),
  IsComplex: optional(boolean()),
  IsExtendedTradingHoursEnabled: optional(boolean()),
  IsOcoOrderSupported: boolean(),
  IsPEAEligible: boolean(),
  IsPEASMEEligible: boolean(),
  IsRedemptionByAmounts: boolean(),
  IsSwitchBySameCurrency: boolean(),
  IsSystematicInternaliser: boolean(),
  IsTradable: boolean(),
  LotSize: optional(number()),
  LotSizeType: LotSizeType.extract(['BuyOnly', 'NotUsed', 'OddLotsNotAllowed']),
  MinimumLotSize: optional(number()),
  MinimumTradeSize: optional(number()),
  NonTradableReason: NonTradableReason.extract([
    'None',
    'ETFsWithoutKIIDs',
    'NotOnlineClientTradable',
    'ReduceOnlyInstrument',
  ]),
  OrderDistances: OrderDistances,
  OrderSetting: optional(OrderSetting),
  PriceCurrency: Currency3,
  PriceToContractFactor: optional(number()),
  PrimaryListing: optional(integer()),
  RelatedInstruments: optional(array(InstrumentKey)),
  RelatedOptionRoots: optional(array(integer())),
  RelatedOptionRootsEnhanced: optional(array(RelatedOptionRoot)),
  StandardAmounts: array(number()),
  SupportedOrderTriggerPriceTypes: optional(array(OrderTriggerPriceType.extract(['LastTraded', 'Open']))),
  SupportedOrderTypes: array(
    PlaceableOrderType.extract([
      'Limit',
      'Market',
      'StopLimit',
      'StopIfTraded',
      'TrailingStopIfTraded',
      'TriggerBreakout',
      'TriggerLimit',
      'TriggerStop',
    ]),
  ),
  SupportedOrderTypeSettings: array(props({
    DurationTypes: array(
      OrderDurationType.extract(['DayOrder', 'FillOrKill', 'GoodTillCancel', 'GoodTillDate', 'ImmediateOrCancel']),
    ),
    OrderType: PlaceableOrderType.extract([
      'Limit',
      'Market',
      'StopLimit',
      'StopIfTraded',
      'TrailingStopIfTraded',
      'TriggerBreakout',
      'TriggerLimit',
      'TriggerStop',
    ]),
  })),
  SupportedStrategies: optional(
    array(
      SupportedStrategyType.extract([
        'Dark',
        'Iceberg',
        'Implementation Shortfall',
        'Limit on Close (LOC)',
        'Liquidity Seeking',
        'Market on Close (MOC)',
        'Nordic@Mid',
        'Pre-Market Limit',
        'Price Peg',
        'Target Close',
        'TWAP',
        'VWAP',
        'With Volume',
      ]),
    ),
  ),
  Symbol: string(),
  TickSize: optional(number()),
  TickSizeScheme: optional(TickSizeScheme),
  TradableAs: optional(array(AssetType.extract(['Etf']))),
  TradableOn: array(format('positive-integer')),
  TradingSessions: InstrumentTradeSessions,
  TradingSignals: TradingSignal,
  TradingStatus: TradingStatus,
  Uic: integer(),
  UnderlyingTypeCategory: UnderlyingTypeCategory,
})

export interface InstrumentDetailsEtn extends GuardType<typeof InstrumentDetailsEtn> {}
export const InstrumentDetailsEtn = props({
  AssetType: literal('Etn'),
  AffiliateInfoRequired: boolean(),
  AmountDecimals: integer(),
  CurrencyCode: Currency3,
  DefaultAmount: number(),
  DefaultSlippage: number(),
  DefaultSlippageType: DefaultSlippageType.extract(['Ticks']),
  Description: string(),
  Exchange: ExchangeSummary,
  Format: PriceDisplayFormat,
  FractionalMinimumLotSize: optional(number()),
  GroupId: integer(),
  IncrementSize: number(),
  IsBailIn: optional(boolean()),
  IsBarrierEqualsStrike: boolean(),
  IsComplex: boolean(),
  IsExtendedTradingHoursEnabled: optional(boolean()),
  IsOcoOrderSupported: boolean(),
  IsPEAEligible: boolean(),
  IsPEASMEEligible: boolean(),
  IsRedemptionByAmounts: boolean(),
  IsSwitchBySameCurrency: boolean(),
  IsSystematicInternaliser: boolean(),
  IsTradable: boolean(),
  LotSizeType: LotSizeType.extract(['NotUsed', 'OddLotsNotAllowed']),
  MinimumLotSize: optional(number()),
  MinimumTradeSize: optional(number()),
  NonTradableReason: NonTradableReason.extract([
    'ETFsWithoutKIIDs',
    'None',
    'NotOnlineClientTradable',
    'ReduceOnlyInstrument',
  ]),
  OrderDistances: OrderDistances,
  OrderSetting: optional(OrderSetting),
  PriceCurrency: Currency3,
  PriceToContractFactor: optional(number()),
  PrimaryListing: optional(integer()),
  RelatedInstruments: optional(array(InstrumentKey)),
  RelatedOptionRoots: optional(array(integer())),
  RelatedOptionRootsEnhanced: optional(array(RelatedOptionRoot)),
  StandardAmounts: array(number()),
  SupportedOrderTriggerPriceTypes: optional(array(OrderTriggerPriceType.extract(['LastTraded', 'Open']))),
  SupportedOrderTypes: array(
    PlaceableOrderType.extract([
      'Limit',
      'Market',
      'StopLimit',
      'StopIfTraded',
      'TrailingStopIfTraded',
      'TriggerBreakout',
      'TriggerLimit',
      'TriggerStop',
    ]),
  ),
  SupportedOrderTypeSettings: array(props({
    DurationTypes: array(
      OrderDurationType.extract(['DayOrder', 'FillOrKill', 'GoodTillCancel', 'GoodTillDate', 'ImmediateOrCancel']),
    ),
    OrderType: PlaceableOrderType.extract([
      'Limit',
      'Market',
      'StopLimit',
      'StopIfTraded',
      'TrailingStopIfTraded',
      'TriggerBreakout',
      'TriggerLimit',
      'TriggerStop',
    ]),
  })),
  SupportedStrategies: optional(
    array(
      SupportedStrategyType.extract([
        'Dark',
        'Iceberg',
        'Implementation Shortfall',
        'Limit on Close (LOC)',
        'Liquidity Seeking',
        'Market on Close (MOC)',
        'Pre-Market Limit',
        'Price Peg',
        'Target Close',
        'TWAP',
        'VWAP',
        'With Volume',
      ]),
    ),
  ),
  Symbol: string(),
  TickSize: optional(number()),
  TickSizeScheme: optional(TickSizeScheme),
  TradableAs: optional(array(literal('Etn'))),
  TradableOn: array(format('positive-integer')),
  TradingSessions: InstrumentTradeSessions,
  TradingSignals: TradingSignal,
  TradingStatus: TradingStatus,
  Uic: integer(),
  UnderlyingTypeCategory: UnderlyingTypeCategory,
})

export interface InstrumentDetailsFund extends GuardType<typeof InstrumentDetailsFund> {}
export const InstrumentDetailsFund = props({
  AssetType: literal('Fund'),
  AffiliateInfoRequired: boolean(),
  AmountDecimals: integer(),
  CanParticipateIn: optional(array(literal('SavingsPlan'))),
  CurrencyCode: Currency3,
  DefaultAmount: number(),
  DefaultSlippage: number(),
  DefaultSlippageType: DefaultSlippageType,
  Description: string(),
  Exchange: ExchangeSummary,
  Format: PriceDisplayFormat,
  FractionalMinimumLotSize: optional(number()),
  GroupId: integer(),
  IncrementSize: number(),
  IsBailIn: optional(boolean()),
  IsBarrierEqualsStrike: boolean(),
  IsComplex: optional(boolean()),
  IsExtendedTradingHoursEnabled: optional(boolean()),
  IsOcoOrderSupported: boolean(),
  IsPEAEligible: boolean(),
  IsPEASMEEligible: boolean(),
  IsRedemptionByAmounts: boolean(),
  IsSwitchBySameCurrency: boolean(),
  IsSystematicInternaliser: boolean(),
  IsTradable: boolean(),
  LotSize: optional(number()),
  LotSizeType: LotSizeType,
  MinimumLotSize: optional(number()),
  MinimumOrderValue: optional(number()),
  MinimumTradeSize: optional(number()),
  NonTradableReason: NonTradableReason,
  OrderDistances: OrderDistances,
  OrderSetting: optional(OrderSetting),
  PriceCurrency: Currency3,
  PriceToContractFactor: optional(number()),
  PrimaryListing: optional(integer()),
  RelatedInstruments: optional(array(InstrumentKey)),
  RelatedOptionRoots: optional(array(integer())),
  RelatedOptionRootsEnhanced: optional(array(RelatedOptionRoot)),
  StandardAmounts: array(number()),
  SupportedOrderTriggerPriceTypes: optional(array(OrderTriggerPriceType)),
  SupportedOrderTypes: array(PlaceableOrderType),
  SupportedOrderTypeSettings: array(SupportedOrderTypeSetting),
  SupportedStrategies: optional(array(SupportedStrategyType.extract([
    'Iceberg',
    'VWAP',
    'With Volume',
    'Implementation Shortfall',
    'TWAP',
    'Market on Close (MOC)',
    'Dark',
    'Liquidity Seeking',
    'Limit on Close (LOC)',
    'Target Close',
    'Price Peg',
    'Pre-Market Limit',
  ]))),
  Symbol: string(),
  TickSize: optional(number()),
  TickSizeScheme: optional(TickSizeScheme),
  TradableAs: optional(array(AssetType.extract(['Fund']))),
  TradableOn: array(format('positive-integer')),
  TradingSessions: InstrumentTradeSessions,
  TradingSignals: TradingSignal,
  TradingStatus: TradingStatus,
  Uic: integer(),
  UnderlyingTypeCategory: UnderlyingTypeCategory,
})

export interface InstrumentDetailsFuturesStrategy extends GuardType<typeof InstrumentDetailsFuturesStrategy> {}
export const InstrumentDetailsFuturesStrategy = props({
  AssetType: literal('FuturesStrategy'),
  AffiliateInfoRequired: boolean(),
  AmountDecimals: integer(),
  ContractSize: integer({ minimum: 1 }),
  CurrencyCode: Currency3,
  DefaultAmount: number(),
  DefaultSlippage: number(),
  DefaultSlippageType: DefaultSlippageType,
  Description: string(),
  Exchange: ExchangeSummary,
  ExpiryDate: format('gregorian-date'),
  Format: PriceDisplayFormat,
  GroupId: integer(),
  IncrementSize: number(),
  IsBarrierEqualsStrike: boolean(),
  IsComplex: boolean(),
  IsOcoOrderSupported: boolean(),
  IsPEAEligible: boolean(),
  IsPEASMEEligible: boolean(),
  IsPitTraded: boolean(),
  IsRedemptionByAmounts: boolean(),
  IsSwitchBySameCurrency: boolean(),
  IsTradable: boolean(),
  Legs: array(StrategyLeg),
  LotSizeText: optional(string()),
  LotSizeType: LotSizeType,
  MinimumTradeSize: number(),
  MinimumLotSize: optional(number()),
  NonTradableReason: NonTradableReason,
  NoticeDate: optional(format('gregorian-date')),
  OrderDistances: OrderDistances,
  // OrderSetting: OrderSetting,
  PriceToContractFactor: number(),
  PriceCurrency: Currency3,
  PrimaryListing: integer(),
  RelatedInstruments: optional(array(InstrumentKey)),
  RelatedOptionRoots: optional(array(integer())),
  RelatedOptionRootsEnhanced: optional(array(RelatedOptionRoot)),
  StandardAmounts: array(number()),
  StrategyType,
  // SupportedOrderTriggerPriceTypes: array(OrderTriggerPriceType),
  SupportedOrderTypes: array(PlaceableOrderType),
  SupportedOrderTypeSettings: array(SupportedOrderTypeSetting),
  Symbol: string(),
  TickSize: number(),
  TradableAs: optional(array(AssetType.extract(['FuturesStrategy']))),
  TradableOn: array(format('positive-integer')),
  TradingSessions: InstrumentTradeSessions,
  TradingSignals: TradingSignal,
  TradingStatus: TradingStatus,
  Uic: integer(),
  UnderlyingTypeCategory: UnderlyingTypeCategory,
})

export interface InstrumentDetailsFxForwards extends GuardType<typeof InstrumentDetailsFxForwards> {}
export const InstrumentDetailsFxForwards = props({
  AssetType: literal('FxForwards'),
  AffiliateInfoRequired: boolean(),
  AmountDecimals: integer(),
  CurrencyCode: Currency3,
  DefaultAmount: number(),
  DefaultSlippage: number(),
  DefaultSlippageType: DefaultSlippageType,
  DisplayHint: optional(DisplayHintType),
  Description: string(),
  Exchange: ExchangeSummary,
  Format: PriceDisplayFormat,
  FxForwardMaxForwardDate: format('date-iso8601'),
  FxForwardMinForwardDate: format('date-iso8601'),
  FxSpotDate: format('date-iso8601'),
  GroupId: integer(),
  IncrementSize: number(),
  IsBarrierEqualsStrike: boolean(),
  IsComplex: boolean(),
  IsOcoOrderSupported: boolean(),
  IsPEAEligible: boolean(),
  IsPEASMEEligible: boolean(),
  IsRedemptionByAmounts: boolean(),
  IsSwitchBySameCurrency: boolean(),
  IsTradable: boolean(),
  LotSizeType: LotSizeType,
  MinimumTradeSize: number(),
  NonTradableReason: NonTradableReason,
  OrderDistances: OrderDistances,
  StandardAmounts: array(number()),
  SupportedOrderTypes: array(PlaceableOrderType),
  SupportedOrderTypeSettings: array(SupportedOrderTypeSetting),
  Symbol: string(),
  TickSize: number(),
  TickSizeLimitOrder: number(),
  TickSizeStopOrder: number(),
  TradableAs: array(AssetType.extract(['FxSpot', 'FxForwards', 'FxSwap', 'FxVanillaOption'])),
  TradableOn: array(format('positive-integer')),
  TradingSessions: InstrumentTradeSessions,
  TradingSignals: TradingSignal,
  TradingStatus: TradingStatus,
  Uic: integer(),
  UnderlyingAssetType: AssetType.extract(['FxSpot']),
  UnderlyingTypeCategory: UnderlyingTypeCategory,
  UnderlyingUic: integer(),
})

export interface InstrumentDetailsFxNoTouchOption extends GuardType<typeof InstrumentDetailsFxNoTouchOption> {}
export const InstrumentDetailsFxNoTouchOption = props({
  AssetType: literal('FxNoTouchOption'),
  AffiliateInfoRequired: boolean(),
  AmountDecimals: integer(),
  CurrencyCode: Currency3,
  DefaultAmount: number(),
  Description: string(),
  Exchange: ExchangeSummary,
  Format: PriceDisplayFormat,
  FxForwardMaxForwardDate: format('date-iso8601'),
  FxForwardMinForwardDate: format('date-iso8601'),
  GroupId: integer(),
  IncrementSize: number(),
  IsBarrierEqualsStrike: boolean(),
  IsComplex: boolean(),
  IsOcoOrderSupported: boolean(),
  IsPEAEligible: boolean(),
  IsPEASMEEligible: boolean(),
  IsRedemptionByAmounts: boolean(),
  IsSwitchBySameCurrency: boolean(),
  IsTradable: boolean(),
  LotSizeType: LotSizeType,
  MinimumTradeSize: number(),
  NonTradableReason: NonTradableReason,
  OptionsChainSubscriptionAllowed: boolean(),
  StandardAmounts: array(number()),
  Symbol: string(),
  TickSize: number(),
  TradableAs: array(AssetType.extract(['FxNoTouchOption', 'FxSpot', 'FxForwards', 'FxVanillaOption', 'FxSwap'])),
  TradingSessions: InstrumentTradeSessions,
  TradingSignals: TradingSignal,
  TradingStatus: TradingStatus,
  Uic: integer(),
  UnderlyingAssetType: AssetType.extract(['FxSpot']),
  UnderlyingTypeCategory: UnderlyingTypeCategory,
  UnderlyingUic: integer(),
})

export interface InstrumentDetailsFxOneTouchOption extends GuardType<typeof InstrumentDetailsFxOneTouchOption> {}
export const InstrumentDetailsFxOneTouchOption = props({
  AssetType: literal('FxOneTouchOption'),
  AffiliateInfoRequired: boolean(),
  AmountDecimals: integer(),
  CurrencyCode: Currency3,
  DefaultAmount: number(),
  Description: string(),
  Exchange: ExchangeSummary,
  Format: PriceDisplayFormat,
  FxForwardMaxForwardDate: format('date-iso8601'),
  FxForwardMinForwardDate: format('date-iso8601'),
  GroupId: integer(),
  IncrementSize: number(),
  IsBarrierEqualsStrike: boolean(),
  IsComplex: boolean(),
  IsOcoOrderSupported: boolean(),
  IsPEAEligible: boolean(),
  IsPEASMEEligible: boolean(),
  IsRedemptionByAmounts: boolean(),
  IsSwitchBySameCurrency: boolean(),
  IsTradable: boolean(),
  LotSizeType: LotSizeType,
  MinimumTradeSize: number(),
  NonTradableReason: NonTradableReason,
  OptionsChainSubscriptionAllowed: boolean(),
  StandardAmounts: array(number()),
  Symbol: string(),
  TickSize: number(),
  TradableAs: array(AssetType.extract(['FxVanillaOption', 'FxSpot', 'FxForwards', 'FxSwap'])),
  TradingSessions: InstrumentTradeSessions,
  TradingSignals: TradingSignal,
  TradingStatus: TradingStatus,
  Uic: integer(),
  UnderlyingAssetType: AssetType.extract(['FxSpot']),
  UnderlyingTypeCategory: UnderlyingTypeCategory,
  UnderlyingUic: integer(),
})

export interface InstrumentDetailsFxSpot extends GuardType<typeof InstrumentDetailsFxSpot> {}
export const InstrumentDetailsFxSpot = props({
  AssetType: literal('FxSpot'),
  AffiliateInfoRequired: boolean(),
  AmountDecimals: integer(),
  CurrencyCode: Currency3,
  DefaultAmount: number(),
  DefaultSlippage: number(),
  DefaultSlippageType: DefaultSlippageType,
  Description: string(),
  DisplayHint: optional(DisplayHintType),
  Exchange: ExchangeSummary,
  Format: PriceDisplayFormat,
  FxForwardMaxForwardDate: optional(format('date-iso8601')),
  FxForwardMinForwardDate: optional(format('date-iso8601')),
  FxSpotDate: format('date-iso8601'),
  GroupId: integer(),
  IncrementSize: number(),
  IsBarrierEqualsStrike: boolean(),
  IsComplex: boolean(),
  IsOcoOrderSupported: boolean(),
  IsPEAEligible: boolean(),
  IsPEASMEEligible: boolean(),
  IsRedemptionByAmounts: boolean(),
  IsSwitchBySameCurrency: boolean(),
  IsTradable: boolean(),
  LotSizeType: LotSizeType,
  MinimumTradeSize: number(),
  NonTradableReason: NonTradableReason,
  OrderDistances: OrderDistances,
  StandardAmounts: array(number()),
  SupportedOrderTypes: array(PlaceableOrderType.extract([
    'Market',
    'Stop',
    'TrailingStop',
    'StopLimit',
    'Limit',
  ])),
  SupportedOrderTypeSettings: array(props({
    OrderType: PlaceableOrderType.extract([
      'Market',
      'Stop',
      'TrailingStop',
      'StopLimit',
      'Limit',
    ]),
    DurationTypes: array(OrderDurationType.extract([
      'DayOrder',
      'GoodTillCancel',
      'GoodTillDate',
      'ImmediateOrCancel',
    ])),
  })),
  Symbol: string(),
  TickSize: number(),
  TickSizeLimitOrder: number(),
  TickSizeStopOrder: number(),
  TradableAs: array(AssetType.extract(['FxVanillaOption', 'FxSpot', 'FxForwards', 'FxSwap'])),
  TradableOn: array(format('positive-integer')),
  TradingSessions: InstrumentTradeSessions,
  TradingSignals: TradingSignal,
  TradingStatus: TradingStatus,
  Uic: integer(),
  UnderlyingTypeCategory: UnderlyingTypeCategory,
})

export interface InstrumentDetailsFxSwap extends GuardType<typeof InstrumentDetailsFxSwap> {}
export const InstrumentDetailsFxSwap = props({
  AssetType: literal('FxSwap'),
  AffiliateInfoRequired: boolean(),
  AmountDecimals: integer(),
  CurrencyCode: Currency3,
  DefaultAmount: number(),
  DefaultSlippage: number(),
  DefaultSlippageType: DefaultSlippageType,
  Description: string(),
  DisplayHint: optional(DisplayHintType),
  Exchange: ExchangeSummary,
  Format: PriceDisplayFormat,
  FxForwardMaxForwardDate: format('date-iso8601'),
  FxForwardMinForwardDate: format('date-iso8601'),
  FxSpotDate: format('date-iso8601'),
  GroupId: integer(),
  IncrementSize: number(),
  IsBarrierEqualsStrike: boolean(),
  IsComplex: boolean(),
  IsOcoOrderSupported: boolean(),
  IsPEAEligible: boolean(),
  IsPEASMEEligible: boolean(),
  IsRedemptionByAmounts: boolean(),
  IsSwitchBySameCurrency: boolean(),
  IsTradable: boolean(),
  LotSizeType: LotSizeType,
  MinimumTradeSize: number(),
  NonTradableReason: NonTradableReason,
  OrderDistances: OrderDistances,
  StandardAmounts: array(number()),
  SupportedOrderTypes: array(PlaceableOrderType.extract([
    'Limit',
    'Market',
  ])),
  SupportedOrderTypeSettings: array(props({
    OrderType: PlaceableOrderType.extract([
      'Limit',
      'Market',
    ]),
    DurationTypes: array(OrderDurationType.extract([
      'FillOrKill',
    ])),
  })),
  Symbol: string(),
  TickSize: number(),
  TickSizeLimitOrder: number(),
  TickSizeStopOrder: number(),
  TradableAs: array(AssetType.extract(['FxSwap', 'FxSpot', 'FxForwards', 'FxVanillaOption'])),
  TradableOn: array(format('positive-integer')),
  TradingSessions: InstrumentTradeSessions,
  TradingSignals: TradingSignal,
  TradingStatus: TradingStatus,
  Uic: integer(),
  UnderlyingAssetType: AssetType.extract(['FxSpot']),
  UnderlyingTypeCategory: UnderlyingTypeCategory,
  UnderlyingUic: integer(),
})

export interface InstrumentDetailsFxVanillaOption extends GuardType<typeof InstrumentDetailsFxVanillaOption> {}
export const InstrumentDetailsFxVanillaOption = props({
  AssetType: literal('FxVanillaOption'),
  AffiliateInfoRequired: boolean(),
  AmountDecimals: integer(),
  CanParticipateInMultiLegOrder: boolean(),
  CurrencyCode: Currency3,
  DefaultAmount: number(),
  Description: string(),
  DisplayHint: optional(DisplayHintType),
  Exchange: ExchangeSummary,
  Format: PriceDisplayFormat,
  FxForwardMaxForwardDate: format('date-iso8601'),
  FxForwardMinForwardDate: format('date-iso8601'),
  GroupId: integer(),
  IncrementSize: number(),
  IsBarrierEqualsStrike: boolean(),
  IsComplex: boolean(),
  IsOcoOrderSupported: boolean(),
  IsPEAEligible: boolean(),
  IsPEASMEEligible: boolean(),
  IsRedemptionByAmounts: boolean(),
  IsSwitchBySameCurrency: boolean(),
  IsTradable: boolean(),
  LotSizeType: LotSizeType,
  MinimumTradeSize: number(),
  NonTradableReason: NonTradableReason,
  OptionsChainSubscriptionAllowed: boolean(),
  StandardAmounts: array(number()),
  Symbol: string(),
  TickSize: number(),
  TradableAs: array(enums(['FxVanillaOption', 'FxSpot', 'FxForwards', 'FxSwap'])),
  TradableOn: array(format('positive-integer')),
  TradingSessions: InstrumentTradeSessions,
  TradingSignals: TradingSignal,
  TradingStatus: TradingStatus,
  Uic: integer(),
  UnderlyingAssetType: literal('FxSpot'),
  UnderlyingTypeCategory: UnderlyingTypeCategory,
  UnderlyingUic: integer(),
})

export interface InstrumentDetailsMutualFund extends GuardType<typeof InstrumentDetailsMutualFund> {}
export const InstrumentDetailsMutualFund = props({
  AdditionalMinimumTradeSize: number(),
  AdditionalMinimumTradeUnits: integer(),
  AssetType: literal('MutualFund'),
  AffiliateInfoRequired: boolean(),
  AmountDecimals: integer(),
  CurrencyCode: Currency3,
  CutOffTimeForSubscriptions: string(), // e.g. "09:30:00"
  DefaultAmount: number(),
  Description: string(),
  DistributionPolicy,
  DividendPeriodicity: optional(DividendPeriodicityType),
  Exchange: ExchangeSummary,
  Format: PriceDisplayFormat,
  FractionalMinimumLotSize: optional(number()),
  GroupId: integer(),
  IncrementSize: number(),
  IsBailIn: optional(boolean()),
  IsBarrierEqualsStrike: boolean(),
  IsComplex: optional(boolean()),
  IsEligibleForSwitch: boolean(),
  IsEligibleForTraspaso: boolean(),
  IsOcoOrderSupported: boolean(),
  IsPEAEligible: boolean(),
  IsPEASMEEligible: boolean(),
  IsRedemptionByAmounts: boolean(),
  IsSwitchBySameCurrency: boolean(),
  IsTradable: boolean(),
  LotSizeType: LotSizeType,
  MinInvestmentAmountValidation: boolean(),
  MinimumTradeSizeCurrency: Currency3,
  MinimumTradeSize: number(),
  MinimumTradeUnits: integer(),
  MfAssetType: optional(MutualFundAssetType),
  NonTradableReason: NonTradableReason,
  OrderDistances: OrderDistances,
  OrderSetting: OrderSetting,
  PriceCurrency: Currency3,
  Rating: integer(),
  RedemptionDays: integer(),
  RedemptionDaysType: DaysType,
  StandardAmounts: array(number()),
  SubscriptionDays: integer(),
  SubscriptionDaysType: DaysType,
  SubscriptionByAmounts: integer(),
  SubscriptionByShares: integer(),
  SupportedOrderTypes: array(PlaceableOrderType.extract([
    'Market',
    'Switch',
    'TraspasoIn',
    'Traspaso',
  ])),
  SupportedOrderTypeSettings: array(props({
    OrderType: PlaceableOrderType.extract([
      'Market',
      'Switch',
      'TraspasoIn',
      'Traspaso',
    ]),
    DurationTypes: array(
      OrderDurationType.extract(['DayOrder', 'GoodTillCancel']),
    ),
  })),
  Symbol: string(),
  TickSize: number(),
  TradableAs: optional(array(AssetType.extract(['MutualFund']))),
  TradableOn: array(format('positive-integer')),
  TradingSessions: InstrumentTradeSessions,
  TradingSignals: TradingSignal,
  TradingStatus: TradingStatus,
  Uic: integer(),
  UnderlyingTypeCategory: UnderlyingTypeCategory,
})

export interface InstrumentDetailsRights extends GuardType<typeof InstrumentDetailsRights> {}
export const InstrumentDetailsRights = props({
  AssetType: literal('Rights'),
  AffiliateInfoRequired: boolean(),
  AmountDecimals: integer(),
  CurrencyCode: Currency3,
  DefaultAmount: number(),
  DefaultSlippage: number(),
  DefaultSlippageType: DefaultSlippageType,
  Description: string(),
  Exchange: optional(ExchangeSummary),
  Format: PriceDisplayFormat,
  FractionalMinimumLotSize: optional(number()),
  GroupId: integer(),
  IncrementSize: number(),
  IsBailIn: optional(boolean()),
  IsBarrierEqualsStrike: boolean(),
  IsComplex: boolean(),
  IsExtendedTradingHoursEnabled: optional(boolean()),
  IsOcoOrderSupported: boolean(),
  IsPEAEligible: boolean(),
  IsPEASMEEligible: boolean(),
  IsRedemptionByAmounts: boolean(),
  IsSwitchBySameCurrency: boolean(),
  IsTradable: boolean(),
  LotSize: optional(number()),
  LotSizeType: LotSizeType,
  MinimumLotSize: optional(number()),
  MinimumTradeSize: optional(number()),
  NonTradableReason: NonTradableReason,
  OrderDistances: OrderDistances,
  OrderSetting: optional(OrderSetting),
  PriceCurrency: Currency3,
  PriceToContractFactor: optional(number()),
  PrimaryListing: integer(),
  RelatedInstruments: optional(array(InstrumentKey)),
  StandardAmounts: array(number()),
  SupportedOrderTriggerPriceTypes: optional(array(OrderTriggerPriceType)),
  SupportedOrderTypes: array(
    PlaceableOrderType.extract([
      'Market',
      'Limit',
      'StopIfTraded',
      'TrailingStopIfTraded',
      'StopLimit',
      'TriggerBreakout',
      'TriggerStop',
      'TriggerLimit',
    ]),
  ),
  SupportedOrderTypeSettings: array(props({
    OrderType: PlaceableOrderType.extract([
      'Market',
      'Limit',
      'StopIfTraded',
      'TrailingStopIfTraded',
      'StopLimit',
      'TriggerBreakout',
      'TriggerStop',
      'TriggerLimit',
    ]),
    DurationTypes: array(
      OrderDurationType.extract(['DayOrder', 'GoodTillCancel', 'GoodTillDate', 'ImmediateOrCancel']),
    ),
  })),
  SupportedStrategies: optional(array(SupportedStrategyType.extract([
    'VWAP',
    'With Volume',
    'Implementation Shortfall',
    'Iceberg',
    'TWAP',
    'Market on Close (MOC)',
    'Liquidity Seeking',
    'Limit on Close (LOC)',
    'Target Close',
    'Price Peg',
    'Pre-Market Limit',
    'Dark',
    'Nordic@Mid',
  ]))),
  Symbol: string(),
  TickSize: optional(number()),
  TickSizeScheme: optional(TickSizeScheme),
  TradableAs: optional(array(AssetType.extract(['Rights']))),
  TradableOn: array(format('positive-integer')),
  TradingSessions: InstrumentTradeSessions,
  TradingSignals: TradingSignal,
  TradingStatus: TradingStatus,
  Uic: integer(),
  UnderlyingTypeCategory: UnderlyingTypeCategory,
})

export interface InstrumentDetailsStock extends GuardType<typeof InstrumentDetailsStock> {}
export const InstrumentDetailsStock = props({
  AssetType: AssetType.extract(['Stock']),
  AffiliateInfoRequired: boolean(),
  AmountDecimals: integer(),
  CurrencyCode: Currency3,
  DefaultAmount: number(),
  DefaultSlippage: number(),
  DefaultSlippageType: DefaultSlippageType.extract(['Ticks']),
  Description: string(),
  Exchange: optional(ExchangeSummary),
  Format: PriceDisplayFormat,
  FractionalMinimumLotSize: optional(number()),
  GroupId: integer(),
  IncrementSize: number(),
  IpoDetails: optional(IpoDetails),
  IsBailIn: optional(boolean()),
  IsBarrierEqualsStrike: boolean(),
  IsComplex: boolean(),
  IsExtendedTradingHoursEnabled: optional(boolean()),
  IsOcoOrderSupported: boolean(),
  IsPEAEligible: boolean(),
  IsPEASMEEligible: boolean(),
  IsRedemptionByAmounts: boolean(),
  IsSwitchBySameCurrency: boolean(),
  IsSystematicInternaliser: boolean(),
  IsTradable: boolean(),
  LotSize: optional(number()),
  LotSizeType: LotSizeType.extract(['BuyOnly', 'NotUsed', 'OddLotsNotAllowed']),
  MinimumLotSize: optional(number()),
  MinimumOrderValue: optional(number()),
  MinimumTradeSize: optional(number()),
  NonTradableReason: NonTradableReason.extract(['None', 'NotOnlineClientTradable', 'ReduceOnlyInstrument']),
  OrderDistances: OrderDistances,
  OrderSetting: optional(OrderSetting),
  PriceCurrency: Currency3,
  PriceToContractFactor: optional(number()),
  PrimaryListing: optional(integer()),
  RelatedInstruments: optional(array(InstrumentKey)),
  RelatedOptionRoots: optional(array(integer())),
  RelatedOptionRootsEnhanced: optional(array(RelatedOptionRoot)),
  StandardAmounts: optional(array(number())),
  SupportedOrderTriggerPriceTypes: optional(array(OrderTriggerPriceType.extract(['LastTraded', 'Open']))),
  SupportedOrderTypes: array(
    PlaceableOrderType.extract([
      'Limit',
      'Market',
      'StopLimit',
      'StopIfTraded',
      'TrailingStopIfTraded',
      'TriggerBreakout',
      'TriggerLimit',
      'TriggerStop',
    ]),
  ),
  SupportedOrderTypeSettings: array(props({
    DurationTypes: array(
      OrderDurationType.extract(['DayOrder', 'GoodTillCancel', 'GoodTillDate', 'ImmediateOrCancel']),
    ),
    OrderType: PlaceableOrderType.extract([
      'Limit',
      'Market',
      'StopIfTraded',
      'StopLimit',
      'TrailingStopIfTraded',
      'TriggerBreakout',
      'TriggerLimit',
      'TriggerStop',
    ]),
  })),
  SupportedStrategies: optional(
    array(
      SupportedStrategyType.extract([
        'Dark',
        'Iceberg',
        'Implementation Shortfall',
        'Limit on Close (LOC)',
        'Liquidity Seeking',
        'Market on Close (MOC)',
        'Nordic@Mid',
        'Pre-Market Limit',
        'Price Peg',
        'Target Close',
        'TWAP',
        'VWAP',
        'With Volume',
      ]),
    ),
  ),
  Symbol: string(),
  TickSize: optional(number()),
  TickSizeScheme: optional(TickSizeScheme),
  TradableAs: optional(array(AssetType.extract(['Stock']))),
  TradableOn: array(format('positive-integer')),
  TradingSessions: InstrumentTradeSessions,
  TradingSignals: TradingSignal,
  TradingStatus: TradingStatus,
  Uic: integer(),
  UnderlyingTypeCategory: UnderlyingTypeCategory,
})

export interface InstrumentDetailsStockIndex extends GuardType<typeof InstrumentDetailsStockIndex> {}
export const InstrumentDetailsStockIndex = props({
  AssetType: literal('StockIndex'),
  AffiliateInfoRequired: boolean(),
  AmountDecimals: integer(),
  CurrencyCode: Currency3,
  DefaultAmount: number(),
  Description: string(),
  Exchange: ExchangeSummary,
  Format: PriceDisplayFormat,
  GroupId: integer(),
  IncrementSize: number(),
  IsBarrierEqualsStrike: boolean(),
  IsOcoOrderSupported: boolean(),
  IsPEAEligible: boolean(),
  IsPEASMEEligible: boolean(),
  IsRedemptionByAmounts: boolean(),
  IsSwitchBySameCurrency: boolean(),
  IsTradable: boolean(),
  LotSizeType: LotSizeType,
  MinimumLotSize: optional(number()),
  NonTradableReason: NonTradableReason,
  // OrderSetting: OrderSetting,
  PriceCurrency: Currency3,
  RelatedInstruments: optional(array(InstrumentKey)),
  RelatedOptionRoots: optional(array(integer())),
  RelatedOptionRootsEnhanced: optional(array(RelatedOptionRoot)),
  SupportedOrderTriggerPriceTypes: array(OrderTriggerPriceType.extract(['LastTraded', 'Open'])),
  SupportedOrderTypes: array(PlaceableOrderType.extract(['Market', 'TriggerBreakout', 'TriggerStop', 'TriggerLimit'])),
  SupportedOrderTypeSettings: array(props({
    OrderType: PlaceableOrderType.extract(['Market', 'TriggerBreakout', 'TriggerStop', 'TriggerLimit']),
    DurationTypes: array(OrderDurationType.extract(['DayOrder', 'GoodTillCancel', 'GoodTillDate'])),
  })),
  Symbol: string(),
  TickSize: optional(number()),
  TickSizeScheme: optional(TickSizeScheme),
  // TradableOn: array(format('positive-integer')),
  TradingSessions: InstrumentTradeSessions,
  TradingSignals: TradingSignal,
  TradingStatus: TradingStatus,
  Uic: integer(),
  UnderlyingTypeCategory: UnderlyingTypeCategory,
})
